D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.csprojResolveAssemblyReference.cache
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.csproj.ResolveComReference.cache
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fAbout.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fAddCustomerInfo.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fBill.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fCustomer.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fManagement.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fLogin.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fBookRoom.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fParameter.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fPrintBill.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fProfile.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fReceiveRoom.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fReport.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fRoom.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fRoomType.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fService.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fServiceType.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fStaff.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.fUseService.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.Properties.Resources.resources
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.csproj.GenerateResource.cache
D:\New folder\HotelManager\HotelManager\obj\Debug\HotelManager.csproj.CoreCompileInputs.cache
D:\New folder\HotelManager\HotelManager\bin\Debug\HotelManager.exe.config
D:\New folder\HotelManager\HotelManager\bin\Debug\HotelManager.exe
D:\New folder\HotelManager\HotelManager\bin\Debug\HotelManager.pdb
D:\New folder\HotelManager\HotelManager\bin\Debug\Bunifu_